defaults: {}

branches:
  - match: develop
    realms:
      - realm: 'totem-development'
        proxy:
         - host: 'spec-python.th.melt.sh'
           paths:
           - path: '/'
             port: 8080
  - match: master
    realms:
      - realm: 'production'
        proxy:
         - host: 'spec-python.au.melt.sh'
           paths:
           - path: '/'
             port: 8080
