defaults: {}

branches:
  - match: develop
    realms:
      - realm: 'totem-development'
        proxy:
         - host: 'spec-python.th.melt.sh'
           paths:
           - path: '/'
             port: 8080
        comptroller: {}
  - match: totem-develop
    realms:
      - realm: 'totem-development1'
        proxy:
         - host: 'spec-python-totem-develop.th.melt.sh'
           paths:
           - path: '/'
             port: 8080
        comptroller: {}
